site_name: cone

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - dart

nav:
    - README: README.md
    - wiki:
        - Home: wiki/Home.md
        - TODOs: wiki/TODOs.md
        - SETUP: wiki/SETUP.md
        - Graphs: wiki/Graphs.md
        - Mobile ledgers: wiki/Mobile-ledgers.md
        - Localizations: wiki/Localizations.md
        - Notes: wiki/Notes.md

extra_css:
  - 'css/extra.css'
