site_name: cone

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - dart

nav:
    - README: README.md
    - wiki:
        - Home: wiki/Home.md
        - TODOs: wiki/TODOs.md
        - SETUP: wiki/SETUP.md
        - Graphs: wiki/Graphs.md
        - Mobile ledgers: wiki/Mobile-ledgers.md
        - Localizations: wiki/Localizations.md
        - Notes: wiki/Notes.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
