site_name: cone

repo_url: https://github.com/bradyt/cone_site/
edit_uri: ""

theme:
    name: mkdocs
    navigation_depth: 3
    highlightjs: true
    hljs_languages:
        - dart

nav:
    - Home: index.md
    - Wiki:
        - Home: wiki/Home.md
        - Mobile ledgers: wiki/Mobile-ledgers.md
        - Notes: wiki/Notes.md
    - Development:
        - TODOs: development/TODOs.md
        - SETUP: development/SETUP.md
        - Graphs: development/Graphs.md
        - Localizations: development/Localizations.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - pymdownx.snippets:
        base_path: docs

extra_css:
  - css/org-mode.css
