site_name: cone

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - dart

nav:
    - Home: index.md
    - TODOs: TODOs.md
    - SETUP: SETUP.md
    - Graphs: Graphs.md
    - Mobile ledgers: Mobile-ledgers.md
    - Localizations: Localizations.md
